[workspace]
channels = ["conda-forge"]
name = "stellaforge"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[feature.pipeline]
channels = ["conda-forge", "bioconda"]

[feature.pipeline.dependencies]
snakemake-minimal = ">=8,<10"
graphviz = ">=9,<15"
pytest = ">=8,<9"

[feature.pipeline.tasks.begin_loop]
cmd = "python -m src.loop"

[environments]
pipeline = { features = ["pipeline"], no-default-feature = true }
