_wandb:
    value:
        cli_version: 0.27.0
        e:
            lrxes7btciseremgjof0ebv9f9dmsxlm:
                apple:
                    ecpuCores: 4
                    gpuCores: 30
                    macModel: Mac15,10
                    memoryGb: 36
                    name: Apple M3 Max
                    pcpuCores: 10
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "23622320128"
                args:
                    - --run-name
                    - HSX_vacuum_ns201_quickrun
                    - --max-trace-runs
                    - "4"
                codePath: tests/stage4-turbulence/SPECTRAX-GK/log_wandb_stage4.py
                codePathLocal: tests/stage4-turbulence/SPECTRAX-GK/log_wandb_stage4.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "952126320640"
                email: zhangyijing2002@gmail.com
                executable: /opt/anaconda3/envs/Stellaforge/bin/python
                git:
                    commit: 98e64a25354e903cc73125f00e778d98e3fd3ecc
                    remote: https://github.com/yijingz02/StellaForge.git
                host: Itsukis-MacBook-Pro.local
                memory:
                    total: "38654705664"
                os: macOS-15.7.4-arm64-arm-64bit
                program: /Users/itsuki/Desktop/PhD/Research/StellaForge/tests/stage4-turbulence/SPECTRAX-GK/log_wandb_stage4.py
                python: CPython 3.10.20
                root: /Users/itsuki/Desktop/PhD/Research/StellaForge
                startedAt: "2026-06-01T08:54:14.336836Z"
                writerId: lrxes7btciseremgjof0ebv9f9dmsxlm
        m: []
        python_version: 3.10.20
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.10.20
            "5": 0.27.0
            "12": 0.27.0
            "13": darwin-arm64
        visualize:
            stage4/final/gamma_vs_rho:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: rho
                        "y": gamma_last
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Gamma vs rho
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: stage4/final/gamma_vs_rho_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            stage4/final/heat_flux_vs_rho:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: rho
                        "y": heat_flux_last
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Heat flux vs rho
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: stage4/final/heat_flux_vs_rho_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            stage4/final/omega_vs_rho:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: rho
                        "y": omega_last
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Omega vs rho
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: stage4/final/omega_vs_rho_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            stage4/final/particle_flux_vs_rho:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: rho
                        "y": particle_flux_last
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Particle flux vs rho
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: stage4/final/particle_flux_vs_rho_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
electron_model:
    value: adiabatic
geometry:
    value:
        a_minor: 0.12150780545936427
        alpha: 0
        geometry_backend: internal
        model: vmec
        npol: 1
grid:
    value:
        Lx: 62.8
        Ly: 62.8
        Nx: 12
        Ny: 12
        Nz: 16
        boundary: fix aspect
        nperiod: 1
        ntheta: 30
        y0: 21
n_runs:
    value: 4
output_dir:
    value: /Users/itsuki/Desktop/PhD/Research/StellaForge/stages/stage4-turbulence/output/HSX_vacuum_ns201_quickrun
output_root:
    value: /Users/itsuki/Desktop/PhD/Research/StellaForge/stages/stage4-turbulence/output
run:
    value:
        Nl: 4
        Nm: 8
        ky: 0.047619047619047616
run_name:
    value: HSX_vacuum_ns201_quickrun
