_wandb:
    value:
        cli_version: 0.26.1
        e:
            udyxuapb5x0drejhsrh8gh68kbqbcb9k:
                args:
                    - --output-dir
                    - stages/stage4-turbulence/output/HSX_vacuum_ns201_quickrun
                    - --progress-log
                    - stages/stage4-turbulence/output/HSX_vacuum_ns201_quickrun/HSX_vacuum_ns201_quickrun.log
                    - --poll-interval-minutes
                    - "10"
                    - --stop-file
                    - stages/stage4-turbulence/output/HSX_vacuum_ns201_quickrun/.wandb-monitor.done
                codePath: tests/stage4-turbulence/SPECTRAX-GK/log_wandb_stage4_concurrent.py
                codePathLocal: tests/stage4-turbulence/SPECTRAX-GK/log_wandb_stage4_concurrent.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "926702559232"
                email: zhangyijing2002@gmail.com
                executable: /Users/itsuki/Desktop/PhD/Research/StellaForge/.pixi/envs/pipeline/bin/python
                git:
                    commit: a8341cdad22ce9aa72758cea2832093838f2e0ec
                    remote: https://github.com/yijingz02/StellaForge.git
                host: Mac.lan
                memory:
                    total: "38654705664"
                os: macOS-15.7.4-arm64-arm-64bit-Mach-O
                program: /Users/itsuki/Desktop/PhD/Research/StellaForge/tests/stage4-turbulence/SPECTRAX-GK/log_wandb_stage4_concurrent.py
                python: CPython 3.13.13
                root: /Users/itsuki/Desktop/PhD/Research/StellaForge
                startedAt: "2026-06-08T06:49:43.132132Z"
                writerId: udyxuapb5x0drejhsrh8gh68kbqbcb9k
        m: []
        python_version: 3.13.13
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.13.13
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
output_dir:
    value: /Users/itsuki/Desktop/PhD/Research/StellaForge/stages/stage4-turbulence/output/HSX_vacuum_ns201_quickrun
output_root:
    value: /Users/itsuki/Desktop/PhD/Research/StellaForge/stages/stage4-turbulence/output
poll_interval_minutes:
    value: 10
progress_log:
    value: /Users/itsuki/Desktop/PhD/Research/StellaForge/stages/stage4-turbulence/output/HSX_vacuum_ns201_quickrun/HSX_vacuum_ns201_quickrun.log
run_name:
    value: HSX_vacuum_ns201_quickrun
